### ISSUE TITLE
harvested_from and donated_to are strings but maybe they should be text?

### ISSUE THREAD

**Issue by ottopchen** [includedavis/farmdavis#8]

**Comment by Bevilacqua** [comment]
Are the columns going to have short entries like names of people or companies if so I think it should be string. If it's longer it should be text. That was my understanding at least. We can go either way!

**Comment by ottopchen** [comment]
I made a migration that changed it to text. From what I read online, in older versions of Rails/PostGres, String was faster for shorter entries, but in newer versions you should always use text cause theres no difference in performance.

Source : http://stackoverflow.com/questions/3354330/difference-between-string-and-text-in-rails
